/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visao;

import Controle.CtrProdutos;
import java.awt.Dimension;
import Modelo.ModProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaguar
 */
public class Produtos extends javax.swing.JInternalFrame {
    
    ModProdutos pro;
    CtrProdutos ctr;
    
    ArrayList<ModProdutos> arrayModProdutos;

    /**
     * Creates new form ModProdutos
     */
    public Produtos() {
        initComponents();
        pro = new ModProdutos();
        ctr = new CtrProdutos();
        arrayModProdutos = new ArrayList<ModProdutos>();
        preencheTabela(ctr.todosProdutos());
    }
    
    public void setPosicao() {  
        Dimension d = this.getDesktopPane().getSize();  
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    private void preencheTabela(ArrayList<ModProdutos> todosProdutos) {
        
        jTProdutos.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTProdutos.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTProdutos.getColumnModel().getColumn(2).setPreferredWidth(3);
        jTProdutos.getColumnModel().getColumn(3).setPreferredWidth(3);
        jTProdutos.getColumnModel().getColumn(4).setPreferredWidth(10);
        
        DefaultTableModel modelo =  (DefaultTableModel) jTProdutos.getModel();
        modelo.setNumRows(0);
        
        this.arrayModProdutos = todosProdutos;

        for (int i = 0; i < todosProdutos.size(); i++) {
            modelo.addRow(new Object[]{todosProdutos.get(i).getPro_id(), todosProdutos.get(i).getPro_descricao(), todosProdutos.get(i).getPro_quantidade(), todosProdutos.get(i).getPro_quantidade_brind(), todosProdutos.get(i).getPro_valor_custo()});
            
        }
    }
    
    private void mostraDados(ModProdutos get) {
        limpaCampos();
        tfNomeProduto.setText(get.getPro_descricao());
        tfId.setText(String.valueOf(get.getPro_id()));
        tfQuant.setText(String.valueOf(get.getPro_quantidade()));
        tfQuantBrind.setText(String.valueOf(get.getPro_quantidade_brind()));
        tfValor.setText(String.valueOf(get.getPro_valor_custo()));
        jCCategoria.setSelectedItem(get.getPro_categoria());
    }
    
    private void limpaCampos() {
        tfCodigoPesquisa.setText("");
        tfId.setText("");
        tfNomePesquisa.setText("");
        tfNomeProduto.setText("");
        tfQuant.setText("");
        tfQuantBrind.setText("");
        tfValor.setText("");
        jCCategoria.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCCategoria = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        tfQuant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfQuantBrind = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfValor = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProdutos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tfCodigoPesquisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfNomePesquisa = new javax.swing.JTextField();
        btPesquisa = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nome Produto:");

        jLabel2.setText("Categoria:");

        jCCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cosmedicos", "Limpeza" }));

        jLabel3.setText("Quantidade Itens:");

        jLabel4.setText("Quantidade Brindes:");

        jLabel5.setText("Valor Produto:");

        jLabel6.setText("Codigo:");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Deletar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQuantBrind, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfNomeProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfValor))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jCCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfQuantBrind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos cadastrados"));

        jTProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Produto", "QTD Itens", "QTD Brindes", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        );

        jLabel7.setText("Codigo:");

        jLabel8.setText("Nome:");

        btPesquisa.setText("Pesquisar");
        btPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfCodigoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfNomePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pro.setPro_id(Integer.parseInt(tfId.getText()));
        pro.setPro_categoria((String) jCCategoria.getSelectedItem());
        pro.setPro_descricao(tfNomeProduto.getText());
        pro.setPro_quantidade(Integer.parseInt(tfQuant.getText()));
        pro.setPro_quantidade_brind(Integer.parseInt(tfQuantBrind.getText()));
        pro.setPro_valor_custo(Double.parseDouble(tfValor.getText()));
        if (ctr.salvar(pro)) {
            JOptionPane.showMessageDialog(null, "Dados Salvos com sucesso");
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao salvar dados");
        }
        limpaCampos();
        preencheTabela(ctr.todosProdutos());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProdutosMouseClicked
        int linhaTabela = jTProdutos.getSelectedRow();
        for(int i = 0; i < this.arrayModProdutos.size(); i++) {
            if ( (int) jTProdutos.getValueAt(linhaTabela, 0) == arrayModProdutos.get(i).getPro_id()) {
                mostraDados(arrayModProdutos.get(i));
                break;
            }    
        }
    }//GEN-LAST:event_jTProdutosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        limpaCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaActionPerformed
        ArrayList<ModProdutos> pesPro = new ArrayList<ModProdutos>();
        
        if (!tfCodigoPesquisa.getText().equals("") && tfNomePesquisa.getText().equals("")) {
            pro.setPro_id(Integer.parseInt(tfCodigoPesquisa.getText()));
            pesPro = ctr.pesquisaProduto(pro, 1);
            
        } else if (tfCodigoPesquisa.getText().equals("") && !tfNomePesquisa.getText().equals("")) {
            pro.setPro_descricao(tfNomePesquisa.getText());
            pesPro =  ctr.pesquisaProduto(pro, 0);
            
        } else if (!tfCodigoPesquisa.getText().equals("") && !tfNomePesquisa.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Não é permitido a pesquisa com os dois campos preechidos");
        else
            JOptionPane.showMessageDialog(null, "É necessario o preenchimento de um dos dois campos da pesquisa");
        
        limpaCampos();
        preencheTabela(pesPro);
    }//GEN-LAST:event_btPesquisaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        pro.setPro_id(Integer.parseInt(tfId.getText()));
        pro.setPro_categoria((String) jCCategoria.getSelectedItem());
        pro.setPro_descricao(tfNomeProduto.getText());
        pro.setPro_quantidade(Integer.parseInt(tfQuant.getText()));
        pro.setPro_quantidade_brind(Integer.parseInt(tfQuantBrind.getText()));
        pro.setPro_valor_custo(Double.parseDouble(tfValor.getText()));
        if (ctr.editar(pro)) {
            JOptionPane.showMessageDialog(null, "Dados Alterados com sucesso");
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Alterar dados");
        }
        preencheTabela(ctr.todosProdutos());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        pro.setPro_id(Integer.parseInt(tfId.getText()));
        pro.setPro_categoria((String) jCCategoria.getSelectedItem());
        pro.setPro_descricao(tfNomeProduto.getText());
        pro.setPro_quantidade(Integer.parseInt(tfQuant.getText()));
        pro.setPro_quantidade_brind(Integer.parseInt(tfQuantBrind.getText()));
        pro.setPro_valor_custo(Double.parseDouble(tfValor.getText()));
        if (ctr.deletar(pro)) {
            JOptionPane.showMessageDialog(null, "Dados Apagados com sucesso");
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao Apagar dados");
        }
        preencheTabela(ctr.todosProdutos());
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProdutos;
    private javax.swing.JTextField tfCodigoPesquisa;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNomePesquisa;
    private javax.swing.JTextField tfNomeProduto;
    private javax.swing.JTextField tfQuant;
    private javax.swing.JTextField tfQuantBrind;
    private javax.swing.JTextField tfValor;
    // End of variables declaration//GEN-END:variables

}
